version: '3.4'

services:
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway\Dockerfile

  accessservice:
    image: ${DOCKER_REGISTRY-}accessservice
    build:
      context: .
      dockerfile: AccessService\Dockerfile
    ports:
      - 2000:80
      - 2001:433


  getremoteservice:
    image: ${DOCKER_REGISTRY-}getremoteservice
    build:
      context: .
      dockerfile: GetRemoteService\Dockerfile
    ports:
      - 3000:80
      - 3001:433

  loggingservice:
    image: ${DOCKER_REGISTRY-}loggingservice
    build:
      context: .
      dockerfile: LoggingService\Dockerfile
    ports:
      - 4000:80
      - 4001:433


  setremoteservice:
    image: ${DOCKER_REGISTRY-}setremoteservice
    build:
      context: .
      dockerfile: SetRemoteService\Dockerfile
    ports:
      - 5000:80
      - 5001:433

